Repository grafana/k6-docs, pull requests merged in 2020-08, with the labels that each got.

#70 New Relic integration with k6 through New Relic StatsD
  src/data/markdown/docs/01 guides/03 Results visualization/NewRelic.md
  src/data/markdown/docs/01 guides/03 Results visualization/images/new-relic-dashboard.png
  src/data/markdown/docs/01 guides/03 Results visualization/images/new-relic-data-explorer.png
Labels: Priority: Medium, documentation, enhancement

#77 Feat/cloud rest api section
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  src/components/blocks/header/nav/header-nav.view.js
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/01 Introduction.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/03 Authentication.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/04 Error Handling.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/05 Organizations.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/06 Tests.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/07 Test Runs.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/08 Test Run Data.md
  src/utils/algolia.js
  src/utils/utils.js
Labels: enhancement

#71 Feature/repo maintenance
  .circleci/config.yml
  .eslintrc
  .github/dependabot.yml
  .huskyrc
  .lintstagedrc
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/blocks/contact-us-form/contact-us-form.module.scss
  src/components/blocks/contact-us-form/contact-us-form.view.js
  src/components/blocks/contact-us-form/contacts-us.story.js
  src/components/blocks/contact-us-form/index.js
  src/components/blocks/contact-us-form/success.inline.svg
  src/components/blocks/contact-us-form/videos/animation.mp4
  src/components/blocks/cta/cta.story.js
  src/components/blocks/header/nav/header-nav.view.js
  src/components/blocks/mobile-nav/mobile-nav.view.js
  src/components/blocks/page-info/page-info.story.js
  src/components/blocks/partners/partners.story.js
  src/components/shared/button/button.story.js
  src/components/shared/checkbox-field/checkbox-field.story.js
  src/components/shared/code/code.story.js
  src/components/shared/field/field.story.js
  src/components/shared/heading/heading.story.js
  src/components/shared/helper-widget/helper-widget.js
  src/components/shared/item-card/item-card.story.js
  src/components/shared/lines/lines.story.js
  src/components/shared/terminal-header/terminal-header.story.js
  src/components/shared/text-field/text-field.story.js
  src/components/shared/trait/trait.story.js
  src/layouts/doc-layout/doc-layout.view.js
  src/templates/docs/integrations.js
  src/utils/algolia.js
  src/utils/utils.js
Labels: maintenance
