Repository grafana/k6-docs, pull requests merged in 2021-07, with the labels that each got.

#349 fix: made sure nav links matching un/slashed uris
  src/layouts/doc-layout/doc-layout.view.js
Labels: Area: Gatsby, Type: Bug

#351 add grafana cloud instruction
  package-lock.json
  src/data/markdown/translated-guides/en/04 Results visualization/05 Grafana Cloud.md
  src/data/markdown/translated-guides/en/04 Results visualization/06 InfluxDB - Grafana.md
  src/data/markdown/translated-guides/en/04 Results visualization/07 JSON.md
  src/data/markdown/translated-guides/en/04 Results visualization/08 Netdata.md
  src/data/markdown/translated-guides/en/04 Results visualization/09 NewRelic.md
  src/data/markdown/translated-guides/en/04 Results visualization/10 StatsD.md
Labels: Area: Community Content, Priority: Medium, Status: Awaiting Review, Type: Enhancement

#356 fix: made sure equal sign won't break anchors
  src/components/shared/heading/heading.view.js
  src/hooks/use-landmark.js
  src/utils/index.js
  src/utils/utils.js
Labels: Area: Gatsby, Priority: Medium

#357 feat: updated logos
  src/components/blocks/header/header.module.scss
  src/images/doc-integrations/k6.png
  src/images/landscape-icon.png
  src/layouts/doc-layout/doc-layout.module.scss
  src/svg/k6.inline.svg
  src/svg/loadimpact.inline.svg
  src/svg/logo.inline.svg
  src/templates/docs/integrations.js
Labels: Area: Gatsby, Priority: High, Type: Enhancement

#361 fix: function typos
  src/hooks/use-landmark.js
  src/utils/utils.js
Labels: Area: Gatsby

#362 fix: fixed container styles for js api page
  src/components/pages/doc-javascript-api/doc-javascript-api.module.scss
  src/templates/docs/javascript-api.js
  src/templates/docs/versioned-javascript-api.js
Labels: Area: Gatsby
