Repository grafana/k6-docs, pull requests merged in 2022-09, with the labels that each got.

#786 Rename cloud environment variables
  src/data/markdown/docs/03 cloud/01 Creating and running a test/02 Cloud tests from the CLI.md
Labels: Area: Cloud Content

#791 Highlight halting/non-halting distinction between thresholds and checks
  src/data/markdown/translated-guides/en/02 Using k6/03 Checks.md
  src/data/markdown/translated-guides/en/02 Using k6/04 Thresholds.md
Labels: Area: Community Content

#802 feat: add categories & type for Extension card
  src/components/pages/doc-extensions/extensions-title-group/extensions-title-group.module.scss
  src/components/shared/extension-card/extension-card.module.scss
  src/components/shared/extension-card/extension-card.view.js
  src/components/shared/page-info/page-info.module.scss
  src/data/doc-extensions/extensions.json
  src/templates/docs/bundle-builder.js
  src/templates/docs/explore-extensions.js
Labels: Status: Awaiting Review
