Repository grafana/k6-docs, pull requests merged in 2022-10, with the labels that each got.

#827 Move CSV and JSON to real-time metrics
  gatsby-node.js
  src/data/markdown/translated-guides/en/03 Results output/000-Overview.md
  src/data/markdown/translated-guides/en/03 Results output/100 End-of-test.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 Amazon CloudWatch.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 Apache Kafka.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 CSV.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 Cloud.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 DataDog.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 Grafana Cloud.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 InfluxDB - Grafana.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 JSON.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 Netdata.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 NewRelic.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 Prometheus.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 StatsD.md
  src/data/markdown/translated-guides/en/03 Results output/200 Real-time/00 TimescaleDB.md
Labels: Structure

#831 Draft: show-more button fix
  src/components/shared/search-box/search-box.view.js
  src/data/markdown/docs/20 jslib/01 jslib/05 aws/SecretsManagerClient/04 deleteSecret(secretID, {{ recoveryWindow 30, noRecovery false }}).md
Labels: Priority: Low, Status: In progress, Area: Gatsby

#842 Rewrites HandleSummary() doc
  src/data/markdown/translated-guides/en/03 Results output/100 End-of-test/150-custom-summary.md
Labels: Area: Community Content, Type: Missing Content

#833 Cloud REST API
  gatsby-node.js
  src/data/markdown/docs/03 cloud/07 Cloud reference/800 Cloud REST API.md
  src/data/markdown/docs/03 cloud/07 Cloud reference/800 Cloud REST API/03 Organizations.md
  src/data/markdown/docs/03 cloud/07 Cloud reference/800 Cloud REST API/04 Tests.md
  src/data/markdown/docs/03 cloud/07 Cloud reference/800 Cloud REST API/05 Test Runs.md
  src/data/markdown/docs/03 cloud/07 Cloud reference/800 Cloud REST API/06 Test Run Metrics.md
  src/data/markdown/docs/03 cloud/07 Cloud reference/800 Cloud REST API/07 Error reference.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/01 Introduction.md
  src/data/markdown/docs/06 Cloud REST API/01 Cloud REST API/02 Authentication.md
Labels: Area: Cloud Content
