Repository grafana/k6-docs, pull requests merged in 2022-07, with the labels that each got.

#718 Documents options for CSV output
  src/data/markdown/translated-guides/en/04 Results visualization/03 CSV.md
Labels: Area: Community Content

#734 Defines thresholds and checks more precisely
  src/data/markdown/translated-guides/en/02 Using k6/03 Checks.md
  src/data/markdown/translated-guides/en/02 Using k6/04 Thresholds.md
  src/data/markdown/translated-guides/en/07 Misc/09 Glossary.md
Labels: Area: Community Content

#737 add admonitions updates
  CONTRIBUTING_FILE_FORMAT.md
  internal-images/blockquote-set-1.jpg
  internal-images/blockquote-set-2.jpg
  src/components/shared/blockquote/blockquote.module.scss
  src/components/shared/blockquote/blockquote.view.js
  src/components/shared/blockquote/svg/attention.inline.svg
  src/components/shared/blockquote/svg/note.inline.svg
  src/components/shared/blockquote/svg/warning.inline.svg
Labels: Area: Gatsby

#741 feat: introduced custom anchors functionality
  CONTRIBUTING_FILE_FORMAT.md
  internal-images/custom-anchors.jpg
  src/components/shared/heading/heading.view.js
  src/data/markdown/translated-guides/en/01 Getting started/02 Installation.md
  src/data/markdown/translated-guides/en/02 Using k6/05 k6 Options/01 How to.md
Labels: Area: Gatsby

#740 Added `DescriptionList` component
  CONTRIBUTING_FILE_FORMAT.md
  internal-images/definition-list.jpg
  src/components/shared/description-list/description-list.module.scss
  src/components/shared/description-list/description-list.view.js
  src/components/shared/description-list/index.js
  src/components/shared/description-list/svg/anchor.inline.svg
  src/components/templates/doc-page/doc-page-content/doc-page-content.view.js
  src/data/markdown/translated-guides/en/02 Using k6/05 k6 Options/01 How to.md
  src/data/markdown/translated-guides/en/07 Misc/09 Glossary.md
  src/svg/anchor.inline.svg
  src/templates/docs/javascript-api.js
  src/templates/docs/versioned-javascript-api.js
Labels: Area: Gatsby, Area: Design
