Repository grafana/k6-docs, pull requests merged in 2022-08, with the labels that each got.

#747 Adds template for execution context
  src/data/markdown/translated-guides/en/02 Using k6/12 Execution context variables.md
Labels: Area: Community Content, Type: Missing Content

#770 chore: deleted dependabot config
  .github/dependabot.yml
Labels: Area: Dependencies

#769 fix: removed link from the rightmost breadcrumb leaf
  src/components/templates/doc-page/breadcrumbs/doc-page-breadcrumbs.module.scss
  src/components/templates/doc-page/breadcrumbs/doc-page-breadcrumbs.view.js
Labels: Area: Gatsby

#774 fix anchors position on mobile screens
  src/components/shared/description-list/description-list.module.scss
  src/components/shared/description-list/description-list.view.js
  src/components/shared/heading/heading.module.scss
  src/components/shared/heading/heading.view.js
Labels: Priority: Low, Area: Design

#767 fix: add fixes to mobile nav
  src/components/blocks/mobile-nav/mobile-nav.module.scss
Labels: Priority: Low, Area: Gatsby, Area: Design

#772 Gatsby; removes inserted slash from og:url
  src/components/shared/seo/seo.view.js
Labels: Area: Gatsby
