Repository grafana/k6-docs, pull requests merged in 2024-11, with the labels that each got.

#1798 Modify fs/streams/csv docs to reflect top-level await support
  docs/sources/k6/next/javascript-api/k6-experimental/csv/Options.md
  docs/sources/k6/next/javascript-api/k6-experimental/csv/Parser.md
  docs/sources/k6/next/javascript-api/k6-experimental/csv/_index.md
  docs/sources/k6/next/javascript-api/k6-experimental/csv/parse.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/FileInfo.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/SeekMode.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/_index.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/file/_index.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/file/read.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/file/seek.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/file/stat.md
  docs/sources/k6/next/javascript-api/k6-experimental/fs/open.md
  docs/sources/k6/next/javascript-api/k6-experimental/streams/_index.md
  docs/sources/k6/next/javascript-api/k6-experimental/streams/readablestreamdefaultcontroller/enqueue.md
Labels: Area: OSS Content

#1803 Update group page to include link to utils check function
  docs/sources/k6/next/javascript-api/k6/group.md
  docs/sources/k6/v0.53.x/javascript-api/k6/group.md
  docs/sources/k6/v0.54.x/javascript-api/k6/group.md
Labels: Area: OSS Content, type/docs

#1802 Add grafana/k6-core team to CODEOWNERS
  CODEOWNERS
Labels: type/docs
