Repository grafana/k6-docs, pull requests merged in 2024-08, with the labels that each got.

#1673 StatsD output scheduled removal
  docs/sources/next/results-output/real-time/amazon-cloudwatch.md
  docs/sources/next/results-output/real-time/datadog.md
  docs/sources/next/results-output/real-time/netdata.md
  docs/sources/next/results-output/real-time/newrelic.md
  docs/sources/next/results-output/real-time/statsd.md
  docs/sources/next/shared/statsd-output.md
Labels: Area: OSS Content

#1689 Replace the 'k6 cloud' references with the new subcommands
  docs/sources/next/get-started/running-k6.md
  docs/sources/next/misc/archive.md
  docs/sources/next/results-output/real-time/cloud.md
  docs/sources/next/set-up/set-up-distributed-k6/troubleshooting.md
  docs/sources/next/using-k6/environment-variables.md
  docs/sources/next/using-k6/k6-options/reference.md
Labels: Area: Cloud Content

#1690 Update WebSocket.binaryType description with the new behavior
  docs/sources/next/javascript-api/k6-experimental/websockets/_index.md
  docs/sources/next/javascript-api/k6-experimental/websockets/blob/_index.md
  docs/sources/next/javascript-api/k6-experimental/websockets/params.md
  docs/sources/next/javascript-api/k6-experimental/websockets/websocket/_index.md
Labels: Area:extensions

#1706 Document `Params.discardResponseMessage` gRPC's option
  docs/sources/next/javascript-api/k6-net-grpc/params.md
Labels: Area: OSS Content
