Repository grafana/k6-docs, pull requests merged in 2024-02, with the labels that each got.

#1498 Update github actions to ones using node20
  .github/workflows/doc-validator.yml
  .github/workflows/pr-deploy.yml
  .github/workflows/production.yml
  .github/workflows/staging.yml
Labels: dependencies

#1492 Fix misleading gRPC connection params defaults
  docs/sources/next/javascript-api/k6-experimental/grpc/client/client-connect-connect-address-params.md
  docs/sources/next/javascript-api/k6-net-grpc/client/client-connect-connect-address-params.md
  docs/sources/v0.47.x/javascript-api/k6-experimental/grpc/client/client-connect-connect-address-params.md
  docs/sources/v0.47.x/javascript-api/k6-net-grpc/client/client-connect-connect-address-params.md
  docs/sources/v0.48.x/javascript-api/k6-experimental/grpc/client/client-connect-connect-address-params.md
  docs/sources/v0.48.x/javascript-api/k6-net-grpc/client/client-connect-connect-address-params.md
  docs/sources/v0.49.x/javascript-api/k6-experimental/grpc/client/client-connect-connect-address-params.md
  docs/sources/v0.49.x/javascript-api/k6-net-grpc/client/client-connect-connect-address-params.md
Labels: Area: OSS Content

#1497 Stop promoting k6/experimental/grpc
  docs/sources/v0.47.x/javascript-api/k6-experimental/grpc/_index.md
  docs/sources/v0.47.x/shared/experimental-grpc-module.md
  docs/sources/v0.48.x/javascript-api/k6-experimental/grpc/_index.md
  docs/sources/v0.48.x/shared/experimental-grpc-module.md
Labels: Area: OSS Content

#1487 Minor changes on constant-arrival-rate docs
  docs/sources/next/using-k6/scenarios/executors/constant-arrival-rate.md
  docs/sources/v0.47.x/using-k6/scenarios/executors/constant-arrival-rate.md
  docs/sources/v0.48.x/using-k6/scenarios/executors/constant-arrival-rate.md
  docs/sources/v0.49.x/using-k6/scenarios/executors/constant-arrival-rate.md
Labels: type/docs

#1513 fix: 404s and build errors
  docs/sources/next/javascript-api/_index.md
  docs/sources/next/javascript-api/jslib/aws/KMSClient/KMSDataKey.md
  docs/sources/next/javascript-api/jslib/aws/KMSClient/generateDataKey.md
  docs/sources/next/javascript-api/jslib/aws/SQSClient/listQueues.md
  docs/sources/next/javascript-api/jslib/aws/SQSClient/sendMessage.md
  docs/sources/v0.47.x/javascript-api/jslib/aws/KMSClient/KMSDataKey.md
  docs/sources/v0.47.x/javascript-api/jslib/aws/KMSClient/generateDataKey.md
  docs/sources/v0.48.x/javascript-api/jslib/aws/KMSClient/KMSDataKey.md
  docs/sources/v0.48.x/javascript-api/jslib/aws/KMSClient/generateDataKey.md
  docs/sources/v0.48.x/javascript-api/jslib/aws/SQSClient/listQueues.md
  docs/sources/v0.48.x/javascript-api/jslib/aws/SQSClient/sendMessage.md
  docs/sources/v0.49.x/javascript-api/_index.md
  docs/sources/v0.49.x/javascript-api/jslib/aws/KMSClient/KMSDataKey.md
  docs/sources/v0.49.x/javascript-api/jslib/aws/KMSClient/generateDataKey.md
  docs/sources/v0.49.x/javascript-api/jslib/aws/SQSClient/_index.md
  docs/sources/v0.49.x/javascript-api/jslib/aws/SQSClient/listQueues.md
  docs/sources/v0.49.x/javascript-api/jslib/aws/SQSClient/sendMessage.md
Labels: type/docs
