Repository grafana/k6-docs, pull requests merged in 2025-08, with the labels that each got.

#2027 Run code blocks with latest k6
  .github/workflows/run-code-blocks.yml
Labels: Area: Tooling/Gatsby

#2034 Updates to Extensions section
  docs/sources/k6/next/extensions/_index.md
  docs/sources/k6/next/extensions/create/_index.md
  docs/sources/k6/next/extensions/create/extensions-registry.md
  docs/sources/k6/next/extensions/create/go-js-bridge.md
  docs/sources/k6/next/extensions/create/javascript-extensions.md
  docs/sources/k6/next/extensions/create/output-extensions.md
  docs/sources/k6/next/extensions/create/secret-source_extensions.md
  docs/sources/k6/next/extensions/explanations/_index.md
  docs/sources/k6/next/extensions/explore.md
  docs/sources/k6/next/extensions/run/_index.md
  docs/sources/k6/v1.2.x/extensions/_index.md
  docs/sources/k6/v1.2.x/extensions/create/_index.md
  docs/sources/k6/v1.2.x/extensions/create/extensions-registry.md
  docs/sources/k6/v1.2.x/extensions/create/go-js-bridge.md
  docs/sources/k6/v1.2.x/extensions/create/javascript-extensions.md
  docs/sources/k6/v1.2.x/extensions/create/output-extensions.md
  docs/sources/k6/v1.2.x/extensions/create/secret-source_extensions.md
  docs/sources/k6/v1.2.x/extensions/explanations/_index.md
  docs/sources/k6/v1.2.x/extensions/explore.md
  docs/sources/k6/v1.2.x/extensions/run/_index.md
Labels: Area:extensions

#2014 Add deploy preview workflow
  .github/workflows/deploy-pr-preview.yml
  docs/sources/k6/next/get-started/resources.md
Labels: Area: Tooling/Gatsby

#2028 k6-operator: add troubleshooting to image with extension
  docs/sources/k6/next/set-up/set-up-distributed-k6/troubleshooting.md
  docs/sources/k6/next/set-up/set-up-distributed-k6/usage/extensions.md
  docs/sources/k6/v1.0.x/set-up/set-up-distributed-k6/troubleshooting.md
  docs/sources/k6/v1.0.x/set-up/set-up-distributed-k6/usage/extensions.md
  docs/sources/k6/v1.1.x/set-up/set-up-distributed-k6/troubleshooting.md
  docs/sources/k6/v1.1.x/set-up/set-up-distributed-k6/usage/extensions.md
  docs/sources/k6/v1.2.x/set-up/set-up-distributed-k6/troubleshooting.md
  docs/sources/k6/v1.2.x/set-up/set-up-distributed-k6/usage/extensions.md
Labels: Area:operator
