Repository grafana/k6-docs, pull requests merged in 2025-09, with the labels that each got.

#2054 Add deprecation notice to instruction for using Grafana k6 Browser Recorder
  docs/sources/k6/next/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.47.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.48.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.49.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.50.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.51.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.52.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.53.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.54.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.55.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.56.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v0.57.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v1.0.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v1.1.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
  docs/sources/k6/v1.2.x/using-k6/test-authoring/create-tests-from-recordings/using-the-browser-recorder.md
Labels: Area: browser

#2053 Add a new guide on creating a script using the openapi-to-k6 converter
  docs/sources/k6/next/using-k6/test-authoring/create-test-script-using-openapi.md
  docs/sources/k6/v1.0.x/using-k6/test-authoring/create-test-script-using-openapi.md
  docs/sources/k6/v1.1.x/using-k6/test-authoring/create-test-script-using-openapi.md
  docs/sources/k6/v1.2.x/using-k6/test-authoring/create-test-script-using-openapi.md
Labels: Area: OSS Content

#2056 Update k6 testing documentation and examples
  docs/sources/k6/_index.md
  docs/sources/k6/next/javascript-api/jslib/testing/_index.md
  docs/sources/k6/v1.2.x/javascript-api/jslib/testing/_index.md
Labels: Area: OSS Content

#2059 Update summary options with deprecation messages
  docs/sources/k6/next/using-k6/k6-options/reference.md
Labels: Area: OSS Content

#2063 Update the link to the white paper
  docs/sources/k6/next/testing-guides/running-large-tests.md
Labels: Area: OSS Content

#2068 Add openapi-to-k6 config options
  docs/sources/k6/next/using-k6/test-authoring/create-test-script-using-openapi.md
Labels: Area: OSS Content

#2052 Add new page for how to run a k6 test
  docs/sources/k6/next/using-k6/assertions.md
  docs/sources/k6/next/using-k6/checks.md
  docs/sources/k6/next/using-k6/cookies.md
  docs/sources/k6/next/using-k6/environment-variables.md
  docs/sources/k6/next/using-k6/execution-context-variables.md
  docs/sources/k6/next/using-k6/http-requests.md
  docs/sources/k6/next/using-k6/javascript-typescript-compatibility-mode.md
  docs/sources/k6/next/using-k6/k6-options/_index.md
  docs/sources/k6/next/using-k6/metrics/_index.md
  docs/sources/k6/next/using-k6/modules.md
  docs/sources/k6/next/using-k6/protocols/_index.md
  docs/sources/k6/next/using-k6/run-k6-test-script.md
  docs/sources/k6/next/using-k6/scenarios/_index.md
  docs/sources/k6/next/using-k6/secret-source/_index.md
  docs/sources/k6/next/using-k6/tags-and-groups.md
  docs/sources/k6/next/using-k6/test-authoring/_index.md
  docs/sources/k6/next/using-k6/test-lifecycle.md
  docs/sources/k6/next/using-k6/thresholds.md
  docs/sources/k6/v1.2.x/using-k6/assertions.md
  docs/sources/k6/v1.2.x/using-k6/checks.md
  docs/sources/k6/v1.2.x/using-k6/cookies.md
  docs/sources/k6/v1.2.x/using-k6/environment-variables.md
  docs/sources/k6/v1.2.x/using-k6/execution-context-variables.md
  docs/sources/k6/v1.2.x/using-k6/http-requests.md
  docs/sources/k6/v1.2.x/using-k6/javascript-typescript-compatibility-mode.md
  docs/sources/k6/v1.2.x/using-k6/k6-options/_index.md
  docs/sources/k6/v1.2.x/using-k6/metrics/_index.md
  docs/sources/k6/v1.2.x/using-k6/modules.md
  docs/sources/k6/v1.2.x/using-k6/protocols/_index.md
  docs/sources/k6/v1.2.x/using-k6/run-k6-test-script.md
  docs/sources/k6/v1.2.x/using-k6/scenarios/_index.md
  docs/sources/k6/v1.2.x/using-k6/secret-source/_index.md
  docs/sources/k6/v1.2.x/using-k6/tags-and-groups.md
  docs/sources/k6/v1.2.x/using-k6/test-authoring/_index.md
  docs/sources/k6/v1.2.x/using-k6/test-lifecycle.md
  docs/sources/k6/v1.2.x/using-k6/thresholds.md
  docs/sources/k6/v1.3.x/using-k6/assertions.md
  docs/sources/k6/v1.3.x/using-k6/checks.md
  docs/sources/k6/v1.3.x/using-k6/cookies.md
  docs/sources/k6/v1.3.x/using-k6/environment-variables.md
  docs/sources/k6/v1.3.x/using-k6/execution-context-variables.md
  docs/sources/k6/v1.3.x/using-k6/http-requests.md
  docs/sources/k6/v1.3.x/using-k6/javascript-typescript-compatibility-mode.md
  docs/sources/k6/v1.3.x/using-k6/k6-options/_index.md
  docs/sources/k6/v1.3.x/using-k6/metrics/_index.md
  docs/sources/k6/v1.3.x/using-k6/modules.md
  docs/sources/k6/v1.3.x/using-k6/protocols/_index.md
  docs/sources/k6/v1.3.x/using-k6/run-k6-test-script.md
  docs/sources/k6/v1.3.x/using-k6/scenarios/_index.md
  docs/sources/k6/v1.3.x/using-k6/secret-source/_index.md
  docs/sources/k6/v1.3.x/using-k6/tags-and-groups.md
  docs/sources/k6/v1.3.x/using-k6/test-authoring/_index.md
  docs/sources/k6/v1.3.x/using-k6/test-lifecycle.md
  docs/sources/k6/v1.3.x/using-k6/thresholds.md
Labels: Area: OSS Content, Area: Cloud Content

#2043 Add Zizmor workflow file
  .github/zizmor.yml
Labels: Area: Tooling/Gatsby
